# Generated by Django 5.2.6 on 2025-10-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_statusmodel_notemodel_count_used_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinemodel',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='statusmodel',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='statusmodel',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
