# Generated by Django 5.2.6 on 2025-10-14 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_disciplinemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.FileField(upload_to='', verbose_name='Местонахождения файла')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('is_tmp', models.BooleanField(default=True)),
            ],
        ),
    ]
