# Generated by Django 5.2.6 on 2025-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_attachcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachcontent',
            old_name='blob',
            new_name='file',
        ),
        migrations.AddField(
            model_name='attachcontent',
            name='user_session',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
