# Generated by Django 5.2.6 on 2025-10-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_rename_blob_attachcontent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachcontent',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='note.notemodel'),
        ),
    ]
