# Generated by Django 5.2.6 on 2025-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_attachcontent_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachcontent',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
