# Generated by Django 5.2.6 on 2025-10-15 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_attachcontent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachcontent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
